### ISSUE TITLE
Merge json file with csv file into geojson file

### ISSUE THREAD

**Issue by DennisH3** [DennisH3/Social-Indicators-Visualization#3]
Can you look into merging the json file and csv file in the code into a geojson file? I've tried looking online and using an online tool [https://funkeinteraktiv.github.io/geo-data-merger/](url), but it doesn't act the way I want it. The output of this tool merges based on the same geographical name (good), but only on the last match from the data file, i.e. age = 65 and older, sex = female, generation status = Third Generation or more, and its respective population size. 

The csv file has been preprocessed to have only the columns of interest and pivoted to be usable.  The output should be that coordinate pairs are also filled/duplicated for every row with the same geography.

Both files can be found on my minIO. 
The json file: CMA_CA_2016_with_Residuals.json
The csv file: 98-400-X2016_reduced_pivoted_data.csv

The choropleth should change colour based on VisMin, and alpha (how opaque the fill is) should depend on Total Income Groups. Population can be filtered by Generation, Age, and Sex. Hovering over the choropleth will display VisMin, Total Income Group, Generation, Age, Sex, and Population.

**Comment by sjchiass** [comment]
@DennisH3 I checked and your JSON file and it is GeoJSON. What you need to do is add your data is a property key:value for the appropriate geography. You can see this here: https://en.wikipedia.org/wiki/GeoJSON

Use a package like [geojsonr](https://cran.r-project.org/web/packages/geojsonR/vignettes/the_geojsonR_package.html) to transform your JSON into a nested list. Then iterate over the polygons and match the appropriate data (.

I am busy with another project, so we'll have to talk further about this later.

**Comment by DennisH3** [comment]
@sjchiass In case you were curious,
To do it in Python: [https://gis.stackexchange.com/questions/287157/add-properties-to-large-geojson](url)
To do it in R: [https://stackoverflow.com/questions/27136009/adding-properties-to-geojson-with-r](url)
